name: Security Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Is (user) input validated, sanitized, and escaped to prevent cross-site scripting, or SQL injection?"
    runs-on: alpine-latest

    steps:
      -
