name: Security Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  "Hello World":
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Success
        run: echo "Success"
