name: Security Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Is (user) input validated, sanitized, and escaped to prevent cross-site scripting, or SQL injection?"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Success
        run: echo "Success"
